index:
   path: /
   controller: App\Controller\HomeController::index

myBids:
   path: /myBids
   controller: App\Controller\HomeController::index

createAuctions:
   path: /createAuctions
   controller: App\Controller\HomeController::index

auctionWithParameter:
   path: /auctions/{id}
   controller: App\Controller\HomeController::index

bidsWithParameter:
   path: /bids/{id}
   controller: App\Controller\HomeController::index

signIn:
   path: /signIn
   controller: App\Controller\SecurityController::index

signUp:
   path: /signUp
   controller: App\Controller\SignUpController::index
